### ISSUE TITLE
Add English Translation 

### ISSUE THREAD

**Issue by saltsoftdrink** [alessioC42/lanis-mobile#160]

**Comment by alessioC42** [comment]
I assume that 95% of our users speak German and will continue to use the German translation. 
However, I personally prefer English UIs and would appreciate a 'select language' feature.
Implementing this feature would require a significant refactoring of the codebase since most of the strings are hard-coded in German. Additionally, many API requests from the SPH are only available in German, either because it's data provided by the school or because of how the API works. 
I would like to see a language picker feature in the future, but we need to focus on improving the core functionality and establishing a solid codebase before implementing it. We are currently doing a lot of code cleanup.

**Comment by alessioC42** [comment]
> I am Italian native speaker

If you don't mind me asking, how did you find the app in the first place? After all, practically every user speaks German because they go to school in Germany/Hesse. 
I find it a bit curious that an Italian finds the project just like that


> Please turn English as high priority.

May not be high, but a little higher than before.

**Comment by alessioC42** [comment]
> exported to many schools around the world, so as to have an app (client + server)

I am really sure that this will not happen. While this app may be open source, this school portal (server) is not. We basically take the website, parse the content and display it in the application. (since it is SSR) It is just a way to make it more convenient to access the data on mobile devices and add some features like push notifications. We are basically providing a specialized on-top solution for our needs as a user of the original system, which is Hesse only. Due to this specialization the software is not as easily adaptable to an open or an other backend. 

> is data encrypted both at rest and in transit

In transit of curse. Because the school portal forces HTTPS, every request must be encrypted. In addition, there is a "second layer encryption" based on RSA within the HTTPS connection for certain sensitive information (such as grades).

At rest, only the password is encrypted on the device. (We cannot save a session or refresh token because the school portal does not work that way. We have to start a new session with the password each time the app starts) Other information is stored in a JSON-like unencrypted format in the app's internal memory. (Currently we do not implement any kind of caching for offline support, so we only store non-sensitive data). An attacker could gain access to the unencrypted storage with a simple debugging interface. With a root shell, he could get the password.

**Comment by alessioC42** [comment]
> PS: do you have a demo profile for testing your app as a "student" and as a "teacher"?

Overlooked.

No. I do not have an account other than mine. I have no control over accounts or servers. So I cannot provide an account.

Also, fancy quantum-safe encryption algorithms have to be implemented on the client and server side. Since I have nothing to do with the official school portal maintainers, I cannot really do anything about it. I am just a 16yo who created a mobile version from the existing web version. So I have a lot of limitations.

**Comment by CodeSpoof** [comment]
> No. I do not have an account other than mine. I have no control over accounts or servers. So I cannot provide an account.

Since the userbase is directly taken from the student records, it wouldn't even be possible for schhols to provide test-accounts.

**Comment by alessioC42** [comment]
The translations should be done with https://github.com/alessioC42/lanis-mobile/commit/d194b5cbbf32f5df78aed35682a290f741e65f4a and will be in the next release. Currently there is no in-app language selection, but I will add that soon!
