### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [alessioC42/lanis-mobile#201]
Please add direct cryptocurrency addresses within the app. All offline. Easy tap and donate without leaving the app: users don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, HBAR, DASH, FTM, XRP, XDC, ADA, XLM, KAS, XMR, SEI, INJ, SUI addresses available for donations (addresses have to be copyable).

Here an integration example made by other developers.

![1000092943](https://github.com/AdamGuidarini/MediTrak/assets/113377431/528e3065-97e2-4851-a590-ecaece5e2727)

**Comment by alessioC42** [comment]
One of the next steps in the development process is the IOS/IpadOS release. This requires an `Apple Developer Account` with an annual fee of 99€. (They manage to make a subscription out of everything :( )

I am currently in correspondence with my school to fiance the listing. And it seems like it will be successful. In Germany, some organizations (e.g. banks) have to provide social financial support. Projects like this are part of it, because it helps in the organization of public schools in Hessen.

I haven't really set up a donation process because there is and will be no need for financial support of the application. 

I also do not really intend to add any kind of donation as long as my school finances the Apple listing. (Gplay was a one-time fee)

**Comment by alessioC42** [comment]
There is no way anyone is going to have any control. Trust me. I'm a really paranoid person and mostly use FOSS software. Also, I don't necessarily have to implement iOS support. If it doesn't happen, it just won't. I am also sure that - at least in this case - they won't have any control over me or whatsoever since I am basically receiving a donation just to finance the listing, not the work itself.
